# Generated by Django 4.1.6 on 2023-02-09 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(
                        blank=True,
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5.0),
                            django.core.validators.MinValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "number_of_rating",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("price", models.IntegerField(blank=True, default=0, null=True)),
                ("is_train_at_home", models.BooleanField(default=False)),
                (
                    "gender_coach_type",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("FM", "Female and Male"),
                        ],
                        max_length=2,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date_joined"),
                ),
                ("is_whatsapp_contact", models.BooleanField(default=True)),
                ("is_phone_contact", models.BooleanField(default=True)),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="location", to="location_app.locationdb"
                    ),
                ),
            ],
        ),
    ]
