# Generated by Django 4.1.6 on 2023-02-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coach_app", "0001_initial"),
        ("person_app", "0001_initial"),
    ]

    operations = [
    ]
