# Generated by Django 4.1.6 on 2023-02-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coach_app", "0001_initial"),
        ("person_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachdb",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coach_detail",
                to="person_app.persondb",
            ),
        ),
    ]
