# Generated by Django 4.1.6 on 2023-02-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coach_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachdb",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
