 # Generated by Django 4.0.4 on 2023-04-16 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0002_remove_persondb_birth_date'),
        ('coach_app', '0003_coachdb_is_confirmed'),
    ]

    operations = [

    ]