# Generated by Django 4.0.4 on 2022-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0012_alter_coachdb_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachdb',
            old_name='price',
            new_name='from_price',
        ),
        migrations.AddField(
            model_name='coachdb',
            name='to_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
