# Generated by Django 4.0.4 on 2022-07-09 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0014_coachdb_gender_coach_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='rating',
            field=models.FloatField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
