# Generated by Django 4.0.4 on 2022-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0006_remove_locationdb_coach'),
        ('coach_app', '0015_alter_coachdb_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdb',
            name='locations',
            field=models.ManyToManyField(to='location_app.locationdb'),
        ),
    ]
