# Generated by Django 4.0.4 on 2022-07-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0016_coachdb_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='from_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coachdb',
            name='number_of_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
