# Generated by Django 4.0.4 on 2022-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0006_remove_locationdb_coach'),
        ('coach_app', '0017_alter_coachdb_from_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coachdb',
            old_name='from_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='coachdb',
            name='to_price',
        ),
        migrations.AlterField(
            model_name='coachdb',
            name='locations',
            field=models.ManyToManyField(related_name='location', to='location_app.locationdb'),
        ),
    ]
