# Generated by Django 4.0.4 on 2023-01-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0018_rename_from_price_coachdb_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdb',
            name='is_whatsapp_contact',
            field=models.BooleanField(default=False),
        ),
    ]
