# Generated by Django 4.0.4 on 2023-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0019_coachdb_is_whatsapp_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdb',
            name='is_phone_contact',
            field=models.BooleanField(default=False),
        ),
    ]
