# Generated by Django 4.0.4 on 2023-02-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0020_coachdb_is_phone_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachdb',
            name='is_phone_contact',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coachdb',
            name='is_whatsapp_contact',
            field=models.BooleanField(default=True),
        ),
    ]
