# Generated by Django 4.0.4 on 2023-02-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0021_alter_coachdb_is_phone_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdb',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
