# Generated by Django 4.1.6 on 2023-02-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("person_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TraineeDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="person",
                        to="person_app.persondb",
                    ),
                ),
            ],
        ),
    ]
