# Generated by Django 4.1.6 on 2023-02-09 19:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coach_app", "0001_initial"),
        ("person_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RatingDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                ("review", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rating",
                        to="person_app.persondb",
                    ),
                ),
                (
                    "rating_coach_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="coach_app.coachdb",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ratingdb",
            constraint=models.UniqueConstraint(
                fields=("person_id", "rating_coach_id"), name="unique_rates"
            ),
        ),
    ]
