# Generated by Django 4.0.4 on 2022-07-09 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0004_auto_20211223_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdb',
            name='rating',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
