# Generated by Django 4.0.4 on 2023-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0006_ratingdb_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingdb',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
