# Generated by Django 4.0.4 on 2022-07-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location_app', '0005_alter_locationdb_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdb',
            name='coach',
        ),
    ]
