# Generated by Django 4.1.6 on 2023-02-09 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sport_type_app", "0001_initial"),
        ("job_type_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("D", "Different")],
                        max_length=1,
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                (
                    "profile_image_s3_path",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("business_email", models.EmailField(max_length=254, null=True)),
                (
                    "instagram_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("youtube_url", models.URLField(blank=True, max_length=500, null=True)),
                ("tiktok_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "facebook_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("fav_sport", models.ManyToManyField(to="sport_type_app.sporttypedb")),
                ("job_type", models.ManyToManyField(to="job_type_app.jobtypedb")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
