# Generated by Django 4.1.6 on 2023-02-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("person_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="persondb",
            name="birth_date",
        ),
    ]
