# Generated by Django 4.0.4 on 2022-05-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0007_persondb_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondb',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondb',
            name='tiktok_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persondb',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
