# Generated by Django 4.0.4 on 2022-07-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_type_app', '0001_initial'),
        ('person_app', '0008_persondb_facebook_url_persondb_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondb',
            name='job_type',
            field=models.ManyToManyField(to='job_type_app.jobtypedb'),
        ),
    ]
