# Generated by Django 4.0.4 on 2022-07-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0009_persondb_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persondb',
            name='is_coach',
        ),
    ]
