# Generated by Django 4.0.4 on 2022-09-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0011_remove_persondb_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondb',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
