# Generated by Django 4.0.4 on 2022-09-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_app', '0012_alter_persondb_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondb',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='persondb',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='persondb',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
