# Generated by Django 4.1.6 on 2023-02-09 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("person_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "image_s3_path",
                    models.CharField(
                        blank=True,
                        default="s3://bfit-data-storage/users/user=liad/profile/ts_day=1656547200/liad.png",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("body", models.TextField(blank=True, null=True)),
                ("create_date", models.DateField(auto_now_add=True)),
                ("update_date", models.DateField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post",
                        to="person_app.persondb",
                    ),
                ),
            ],
        ),
    ]
