# Generated by Django 4.0.4 on 2022-07-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_alter_postdb_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='image',
        ),
        migrations.AddField(
            model_name='postdb',
            name='image_s3_path',
            field=models.CharField(blank=True, default='s3://bfit-data-storage/users_images/user=liad/profile/ts_day=1656547200/liad.png', max_length=200, null=True),
        ),
    ]
