# Generated by Django 4.0.4 on 2022-08-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0008_remove_postdb_image_postdb_image_s3_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='image_s3_path',
            field=models.CharField(blank=True, default='s3://bfit-data-storage/users/user=liad/profile/ts_day=1656547200/liad.png', max_length=200, null=True),
        ),
    ]
